apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-test-app-dev
commonLabels:
  app: argocd-test-app-dev
nameSuffix: -dev

patchesStrategicMerge:
- ./deployment-patches.yaml
- ./service-patches.yaml

images:
- name: argocd-test-app
  newName: argocd-test-app-dev
  newTag: "67"

resources:
- ../../base
